local function run(msg, matches)

if matches[1]:lower() == 'spam' then
return [[

The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here
The Hydra Team Is Here

]]
end
end

return {

patterns = {

"^([Ss][Pp][Aa][Mm])$",


},

run = run

}
